### ISSUE TITLE
Bug: Color Picker Issues

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/humhub-scrollup-module#11]
When you click the color picker then navigate to another page the color picker is still displayed.

### How to reproduce
- Navigate to `https://domain.com/scrollup/admin/index`
- Click on the color picker then close it
- Go to another page on your instance

![Screenshot_2](https://user-images.githubusercontent.com/35392110/81035308-6aeecf80-8e68-11ea-81c4-b77cb2f79eca.png)

**Comment by ArchBlood** [comment]
@luke- do you think this is an internal issue with the color picker or the way it was implemented in the module?

**Comment by luke-** [comment]
Looks good for me.

@buddh4 any idea?
