### ISSUE TITLE
HumHub v1.8 Element Loading Issues

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/humhub-scrollup-module#18]
Currently we're investigating some issues with the module on v1.8.0-beta.2

**Comment by ArchBlood** [comment]
Seems to be an issue with cache loading?

**Comment by ArchBlood** [comment]
@buddh4 is there a way to auto clear the cache by cron for such an issue?

**Comment by buddh4** [comment]
Not even sure whats the problem or error is? When updating an module from git you have to manually clear the assets. Not sure if this is the problem?

**Comment by ArchBlood** [comment]
> Not even sure whats the problem or error is? When updating an module from git you have to manually clear the assets. Not sure if this is the problem?

I've been getting reports that on update of modules that affect sections this module is displayed in that elements load abnormally, I've only seen it on installing the tasks module but disabling the scroll up module and clearing cache seems to fix the issue, just wondering if it were possible or a good idea to do such a thing so that this doesn't happen in the future of using this module
