### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by luke-** [GreenMeteor/humhub-scrollup-module#2]
Thanks for the module! For the Marketplace version: can you add another screenshot and in the README file some more description?

**Comment by ArchBlood** [comment]
Sure thing! Was about to do that, just forgot was in a hurry to upload it after the development of the module. :smile:

**Comment by ArchBlood** [comment]
And should be done @luke- :+1:

**Comment by luke-** [comment]
Thank you, cool module!

**Comment by ArchBlood** [comment]
Reopening due to #3, single page loading breaks the JavaScript mechanism.
