### ISSUE TITLE
Enh: Add config option "positions"

### ISSUE THREAD

**Issue by michael79bxl** [GreenMeteor/humhub-scrollup-module#4]
Hi !

Thanks for this great module!

We already have freichat located on bottom right corner.
Could you add a configuration page allowing to choose from 4 positions?
(top-left, top-right, bottom-left and bottom-right)

Regards,

Michael

**Comment by ArchBlood** [comment]
The module as it will be going through a lot of changes in time, sadly this is because of the Pjax single page loading, as for this issue, we'll see if we can do something within the next few weeks as the Pjax issue takes greater priority at this time. :+1:

**Comment by ArchBlood** [comment]
@michael79bxl please test out the changes done in this p/r and give me your thoughts on if this works for you or not. :+1:

**Comment by ArchBlood** [comment]
At the moment only bottom-left and bottom-right are supported, as if it were to support top-left and top-right there could be issues on scrolling.

**Comment by michael79bxl** [comment]
This is just perfect! Thanks 🥇 
My settings: top: 100px; right: 30px;

**Comment by ArchBlood** [comment]
Glad it's to your liking. :smile:
